### ISSUE TITLE
confused getting started in React

### ISSUE THREAD

**Issue by stuartcrobinson** [BEE-Plugin/Bee-plugin-official#96]
would be really nice if there was a single working `quickstart` example demo repo for starting the embedded email building in a new react project.  i tried pulling and running this repo like it suggests but it's not helping

also the readme says "raccomended"

**Comment by stuartcrobinson** [comment]
and typescript please

**Comment by stuartcrobinson** [comment]
i got the code to compile w/o errors but now this weird error when running it:
```

/Users/stuartrobinson/repos/mailpotato/frontend/mk-remix-supabase-public-demo/node_modules/load-script/index.js:3
  var head = document.head || document.getElementsByTagName('head')[0]
             ^
ReferenceError: document is not defined
    at load (/Users/stuartrobinson/repos/mailpotato/frontend/mk-remix-supabase-public-demo/node_modules/load-script/index.js:3:14)
    at load (/Users/stuartrobinson/repos/mailpotato/frontend/mk-remix-supabase-public-demo/node_modules/@mailupinc/bee-plugin/src/index.ts:26:13)
    at Bee.bee (/Users/stuartrobinson/repos/mailpotato/frontend/mk-remix-supabase-public-demo/node_modules/@mailupinc/bee-plugin/src/index.ts:60:26)
    at /Users/stuartrobinson/repos/mailpotato/frontend/mk-remix-supabase-public-demo/node_modules/@mailupinc/bee-plugin/src/index.ts:94:11
    at new Promise (<anonymous>)
```

here's the page:

```
import BeePlugin from '@mailupinc/bee-plugin';
import { template1 } from './bee_template';

const clientId = process.env.PLUGIN_CLIENT_ID as string
const clientSecret = process.env.PLUGIN_CLIENT_SECRET as string
const BEEJS_URL = 'https://app-rsrc.getbee.io/plugin/BeePlugin.js'
const API_AUTH_URL = 'https://auth.getbee.io/apiauth'
const beeTest = new BeePlugin(undefined, { authUrl: API_AUTH_URL, beePluginUrl: BEEJS_URL })
const beeConfig = {
  uid: 'b5e71117-796f-462b-b6f1-669c4e207633', //needed for identify resources of the that user and billing stuff
  container: 'bee-plugin-container', //Identifies the id of div element that contains BEE Plugin
  language: 'en-US',
  onSave: (jsonFile: any, htmlFile: any) => {
    console.log('onSave', jsonFile, htmlFile)
  },
  onSaveAsTemplate: (jsonFile: any) => {
    console.log('onSaveAsTemplate', jsonFile)
  },
  onSend: (htmlFile: any) => {
    console.log('onSend', htmlFile)
  },
  onError: (errorMessage: any) => {
    console.log('onError ', errorMessage)
  }
}
beeTest
  .getToken(clientId, clientSecret)
  .then(() => beeTest.start(beeConfig, template1 as any))
function SastsPage() {
  return <div id="bee-plugin-container">bee-plugin-container</div>;
}
export default SastsPage;
```

this is in Remix.

page loads fine when i comment out this line:
```
beeTest
  .getToken(clientId, clientSecret)
  .then(() => beeTest.start(beeConfig, template1 as any))
```

**Comment by stuartcrobinson** [comment]
found this that got it working for me: https://codesandbox.io/s/bee-plugin-react-typescript-parcel-sample-8q4rg?file=/src/BeePluginStarter.tsx

**Comment by davidesamp** [comment]
H @stuartcrobinson,
Did you solve your problem or do you always get a compile error?

**Comment by stuartcrobinson** [comment]
it's working now thank you for checking.  definitely still recommend a full
example tho
